GET http://localhost/api-platform/answers
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQ4NDM1MTEsImV4cCI6MTY2NDg0NzExMSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.u2zGcG_lRzLZ9zHxcIuTJlwPpre1Rv5yUztJhEzx6eYDWJOVae0BlzUpYhXrZ6EXXcE8TgfMJHmLJYm5H5FCkOOJ1eneR2hCDNkL2xynhTlxCjAL_PgnHh3wYZBFHE-OyLNan-p2pc646OSWlsLrQY_EpRvU-MMVe4hA7V3RPWi32Om5v7CRJiH-XlYD0JFAizxISBUALrP86p49XGF2oujl8d7S2iTfx5tCcSX6jBeyLoXoR4C9J_QRZW8zrAd81KWJyC84Oc2LhAzuHfirXrPyz8yMaOxy5gxj3epzFh7yhBiJHdnyb5DhZ0PBwOC-8wHr60vXHy73hLCmb8GvSQ

###
GET http://localhost/api-platform/answers/3444c782-733a-44be-8279-6d020738964b
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUwNjI1MzEsImV4cCI6MTY2NTA2NjEzMSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.Wf8sbh1U-CJNfC8ZQV1b764l33ykBZZw2u4CiOaRiYUJBx29NcBP2WkMdWeGRMsHnv-NYJIqNWa7frI2LmKi8YY3tNQ51G9u50TCbRrMKUMnBpVDlCLMttXTxAim35nsJoFN4Ur8uPwuQbet-Rjf8tMN8xA4bEIJhwJGsA_UZnE6gpoE1NlHWGcCviJ6eonKbbXbTUfJCyYvJKGz721R1XaTsxgX5uxNnd9XMzQBleaMKiJFBbPWHrfL5E5sEltwrALJJsyKKHQYrvUrI1U7cjae5484IxtiQqnR1vtJxo4Zfga-GybGTyz9uh7BMBpfeX7P0X-GM9DUXVR3UJ9-7g

###
POST http://localhost/api-platform/answers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQ4NDM1MTEsImV4cCI6MTY2NDg0NzExMSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.u2zGcG_lRzLZ9zHxcIuTJlwPpre1Rv5yUztJhEzx6eYDWJOVae0BlzUpYhXrZ6EXXcE8TgfMJHmLJYm5H5FCkOOJ1eneR2hCDNkL2xynhTlxCjAL_PgnHh3wYZBFHE-OyLNan-p2pc646OSWlsLrQY_EpRvU-MMVe4hA7V3RPWi32Om5v7CRJiH-XlYD0JFAizxISBUALrP86p49XGF2oujl8d7S2iTfx5tCcSX6jBeyLoXoR4C9J_QRZW8zrAd81KWJyC84Oc2LhAzuHfirXrPyz8yMaOxy5gxj3epzFh7yhBiJHdnyb5DhZ0PBwOC-8wHr60vXHy73hLCmb8GvSQ

{
  "question": "\/api-platform\/questions\/f424beda-d831-49d2-8696-400eb15736c0",
  "examinationSheet": "\/api-platform\/examination_sheets\/f4e9785e-c426-4f79-80d9-973c4e553c9f"
}
###
PUT http://localhost/api-platform/answers/4770872d-4033-4a02-9996-b3fc7feaec3d
Accept: application/ld+json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQ3MTUyMzMsImV4cCI6MTY2NDcxODgzMywicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.tIrYqfFWoy7vrjk3rVWBIHe8F961PpZ45LFzr9hbJKj1f9gfVEUmoVtkPcP1hsDWvD1WhQ3kxXSWtFEapg43QqbW8IvuHjCLt17CpWCcDuOyygUIRMFiLXyHMbCHnz7PSYulazKOlSz2sQUKDIAjmHk3crXrCCuLDIgDmtCI-cKwDVokmn-C-g6iM4i6XbaY8BeGQPi_4bc0W7s2VtmNZ4gDy79ho0IqY93KiJnWa20OxUTIWpwEnH4VdziaTnYRKLpSBGvprsSpDYpJzizeESX-t-mTyj1pVTVZcrhnmxxP-qn9_3hhl95MqDvEIC1Y_cBs62Y4q6zeb_PlQW480A

{
  "id": "4770872d-4033-4a02-9996-b3fc7feaec3d",
  "content": "Вопрос без лимита времени",
  "timeLimit": 0,
  "ord": 7,
  "exam": "\/api-platform\/exams\/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f",
  "examinationSheets": [],
  "rightAnswers": []
}

###
PATCH http://localhost/api-platform/questions/4770872d-4033-4a02-9996-b3fc7feaec3d
Accept: application/ld+json
Content-Type: application/merge-patch+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQ3MTUyMzMsImV4cCI6MTY2NDcxODgzMywicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.tIrYqfFWoy7vrjk3rVWBIHe8F961PpZ45LFzr9hbJKj1f9gfVEUmoVtkPcP1hsDWvD1WhQ3kxXSWtFEapg43QqbW8IvuHjCLt17CpWCcDuOyygUIRMFiLXyHMbCHnz7PSYulazKOlSz2sQUKDIAjmHk3crXrCCuLDIgDmtCI-cKwDVokmn-C-g6iM4i6XbaY8BeGQPi_4bc0W7s2VtmNZ4gDy79ho0IqY93KiJnWa20OxUTIWpwEnH4VdziaTnYRKLpSBGvprsSpDYpJzizeESX-t-mTyj1pVTVZcrhnmxxP-qn9_3hhl95MqDvEIC1Y_cBs62Y4q6zeb_PlQW480A

{
  "ord": 1
}

###
DELETE http://localhost/api-platform/answers/dba539e8-5b6f-4a40-987c-25e32b654de0
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQ4NDM1MTEsImV4cCI6MTY2NDg0NzExMSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.u2zGcG_lRzLZ9zHxcIuTJlwPpre1Rv5yUztJhEzx6eYDWJOVae0BlzUpYhXrZ6EXXcE8TgfMJHmLJYm5H5FCkOOJ1eneR2hCDNkL2xynhTlxCjAL_PgnHh3wYZBFHE-OyLNan-p2pc646OSWlsLrQY_EpRvU-MMVe4hA7V3RPWi32Om5v7CRJiH-XlYD0JFAizxISBUALrP86p49XGF2oujl8d7S2iTfx5tCcSX6jBeyLoXoR4C9J_QRZW8zrAd81KWJyC84Oc2LhAzuHfirXrPyz8yMaOxy5gxj3epzFh7yhBiJHdnyb5DhZ0PBwOC-8wHr60vXHy73hLCmb8GvSQ
