GET http://localhost/api-courses/new/list
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Njg5NTk2MzYsImV4cCI6MTY2OTA0NjAzNiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.1kDVqGnuSLnET6_VcOZl0Ban1xt-ilNmWz-uobuf1oUBf3zzdluhqc1dITqbwrkkV_EwFPjUx4d8IcZt8rQobF0_hFUMA_ZlIloDzaOGreJOK5rPDPVpmDEe237G2tHmeNDXjKFmBp_yVj9exJUBLwAWY5Y7w-5GJQW7AR4Y-ZvwAQpVbnd9Y3Vn-ISFnnciCA5t5l5amfLG33Cn9IFIyQ1q6-9A2T84Q2nNhhPREEIoWmjWbJR6KbmsuZpIVQtsugoJVRD06Sc4wccSy6A3sAjHAJYWSalzbJW0ogmgZHPg5DQdGF4XssZamyqm2p3otZQta1E01aU_tDlUdT6xAw

###
GET http://localhost/api-courses/started/list
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Njg5NTk2MzYsImV4cCI6MTY2OTA0NjAzNiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.1kDVqGnuSLnET6_VcOZl0Ban1xt-ilNmWz-uobuf1oUBf3zzdluhqc1dITqbwrkkV_EwFPjUx4d8IcZt8rQobF0_hFUMA_ZlIloDzaOGreJOK5rPDPVpmDEe237G2tHmeNDXjKFmBp_yVj9exJUBLwAWY5Y7w-5GJQW7AR4Y-ZvwAQpVbnd9Y3Vn-ISFnnciCA5t5l5amfLG33Cn9IFIyQ1q6-9A2T84Q2nNhhPREEIoWmjWbJR6KbmsuZpIVQtsugoJVRD06Sc4wccSy6A3sAjHAJYWSalzbJW0ogmgZHPg5DQdGF4XssZamyqm2p3otZQta1E01aU_tDlUdT6xAw

###
GET http://localhost/api-courses/completed/list
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Njg5NTk2MzYsImV4cCI6MTY2OTA0NjAzNiwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.1kDVqGnuSLnET6_VcOZl0Ban1xt-ilNmWz-uobuf1oUBf3zzdluhqc1dITqbwrkkV_EwFPjUx4d8IcZt8rQobF0_hFUMA_ZlIloDzaOGreJOK5rPDPVpmDEe237G2tHmeNDXjKFmBp_yVj9exJUBLwAWY5Y7w-5GJQW7AR4Y-ZvwAQpVbnd9Y3Vn-ISFnnciCA5t5l5amfLG33Cn9IFIyQ1q6-9A2T84Q2nNhhPREEIoWmjWbJR6KbmsuZpIVQtsugoJVRD06Sc4wccSy6A3sAjHAJYWSalzbJW0ogmgZHPg5DQdGF4XssZamyqm2p3otZQta1E01aU_tDlUdT6xAw
