GET http://localhost/api-platform/exams
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

###
GET http://localhost/api-platform/exams/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

###
POST http://localhost/api-platform/exams
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

{
  "description": "Тест с id",
  "questions": [],
  "examinationSheets": [],
  "timeLimit": 3600,
  "status": "enable"
}

###
PUT http://localhost/api-platform/exams/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f
Accept: application/ld+json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

{
  "id": "c0b9edc1-bedd-48b0-9a99-64d8bf3f591f",
  "description": "Опросник с лимитом времени",
  "questions": [
    "\/api-platform\/questions\/4770872d-4033-4a02-9996-b3fc7feaec3d",
    "\/api-platform\/questions\/f424beda-d831-49d2-8696-400eb15736c0"
  ],
  "examinationSheets": [
    "\/api-platform\/examination_sheets\/f4e9785e-c426-4f79-80d9-973c4e553c9f"
  ],
  "timeLimit": 3660,
  "status": "enable"
}
###
PATCH http://localhost/api-platform/exams/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f
Accept: application/ld+json
Content-Type: application/merge-patch+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

{
  "timeLimit": 3670
}

###
DELETE http://localhost/api-platform/exams/4bdd0be4-9b37-4118-a5ac-290c3cffe7f6
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA