GET http://localhost/api-platform/exams
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUwNjI1MzEsImV4cCI6MTY2NTA2NjEzMSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.Wf8sbh1U-CJNfC8ZQV1b764l33ykBZZw2u4CiOaRiYUJBx29NcBP2WkMdWeGRMsHnv-NYJIqNWa7frI2LmKi8YY3tNQ51G9u50TCbRrMKUMnBpVDlCLMttXTxAim35nsJoFN4Ur8uPwuQbet-Rjf8tMN8xA4bEIJhwJGsA_UZnE6gpoE1NlHWGcCviJ6eonKbbXbTUfJCyYvJKGz721R1XaTsxgX5uxNnd9XMzQBleaMKiJFBbPWHrfL5E5sEltwrALJJsyKKHQYrvUrI1U7cjae5484IxtiQqnR1vtJxo4Zfga-GybGTyz9uh7BMBpfeX7P0X-GM9DUXVR3UJ9-7g

###
GET http://localhost/api-platform/exams/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

###
GET http://localhost/api-process/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f/start
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUwNjI1MzEsImV4cCI6MTY2NTA2NjEzMSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.Wf8sbh1U-CJNfC8ZQV1b764l33ykBZZw2u4CiOaRiYUJBx29NcBP2WkMdWeGRMsHnv-NYJIqNWa7frI2LmKi8YY3tNQ51G9u50TCbRrMKUMnBpVDlCLMttXTxAim35nsJoFN4Ur8uPwuQbet-Rjf8tMN8xA4bEIJhwJGsA_UZnE6gpoE1NlHWGcCviJ6eonKbbXbTUfJCyYvJKGz721R1XaTsxgX5uxNnd9XMzQBleaMKiJFBbPWHrfL5E5sEltwrALJJsyKKHQYrvUrI1U7cjae5484IxtiQqnR1vtJxo4Zfga-GybGTyz9uh7BMBpfeX7P0X-GM9DUXVR3UJ9-7g

###
GET http://localhost/api-process/a0b92d5c-beeb-45d6-86be-6aee17f2a32e/next/6dddfb44-1a84-4a60-91e0-bb3668d94228
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTU5NjEsImV4cCI6MTY2NTI1OTU2MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZGV2QGRldi5kZXYifQ.MuUVTpN5Re53K2EJoJa3mp1ranl6UkENez-3a3HkenWuS5hsHr0m1_OUVQX2UyrESsJFQmC3inKTSA4WSn9niealaYKhol2Y9gX_Spuv3tvmHu41WkhrUXKQ5Zpx5JJdIzaVZsmrJo7hxV1W_COazqFmFjPbJtuBZIAfxnfOi2BpqJzFafARuZnIWCXMaVBqA7J-Dj8kvzPezr902wYJnMOXDNzLsV7cs126y-LtiRJQplj3ogeSHMBZDs_H58JKlKRA5ejXhif__q4X3DbLvg7gQzKWN79GAwX_XsBcgBmimbDKDLd-rTLsJ1uV8rPWZ645hPgOpZj9iI9TEFEzrg

###
POST http://localhost/api-platform/exams
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNDIzMDcsImV4cCI6MTY2NTI0NTkwNywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InNsdW16QHlhbmRleC5ydSJ9.Kz-qLOY1AjDL87ZMmWGOVSBg72TiHKfBojzKGBUmhUrcRWSvmm9e2Qk44i9SnfGf48idpLSK9IFYZc8ez6d1BeO-no3Wpn_jmpf2OJhyS-tlSnrQLxs5n6jLX-YODT3WEEU_CEQdixmdHFG95b-r7kCIQZKOyqP23kvY0GZ9nlsIRuk3j9Bi52pV0u1dusmFhGCYnDaByFwpzCmrT14XcxS0mvt9JuT4FygRVhhSUuR71RHOIsbfNfGNLZRA2yjzFbm8BB55YdqmDxLhLKYC6PvE6GYpHaC09bjnBxq0EmIMTeeo3IaAcCOIvsDIYY-zp0NHB8Ii-8r6ZWIAzSctlQ

{
  "description": "Тест с id 111",
  "questions": [],
  "examinationSheets": [],
  "timeLimit": 0,
  "status": "enable"
}

###
PUT http://localhost/api-platform/exams/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f
Accept: application/ld+json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

{
  "id": "c0b9edc1-bedd-48b0-9a99-64d8bf3f591f",
  "description": "Опросник с лимитом времени",
  "questions": [
    "\/api-platform\/questions\/4770872d-4033-4a02-9996-b3fc7feaec3d",
    "\/api-platform\/questions\/f424beda-d831-49d2-8696-400eb15736c0"
  ],
  "examinationSheets": [
    "\/api-platform\/examination_sheets\/f4e9785e-c426-4f79-80d9-973c4e553c9f"
  ],
  "timeLimit": 3660,
  "status": "enable"
}
###
PATCH http://localhost/api-platform/exams/c0b9edc1-bedd-48b0-9a99-64d8bf3f591f
Accept: application/ld+json
Content-Type: application/merge-patch+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA

{
  "timeLimit": 3670
}

###
DELETE http://localhost/api-platform/exams/4bdd0be4-9b37-4118-a5ac-290c3cffe7f6
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjQzNzMyNTAsImV4cCI6MTY2NDM3Njg1MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.FmZ5L0FQx0CVsHhEFUq65_aKeUFHvyalcRYlfepOkoojtYrd6a30XAoMzi-Eg7rkM6QzOF7L_sjEpdH-6gv8Mn_CqlOWZiPU7pcjytw_tiMmUzkHJpJ04zKGCRg45-IMoijsEUHkzrFYACgLpDavRWX8O2aVW8TMjo4aWQeh1Ys4y72iBoXxmDJXrRgpmsJ09mwDKnNmANwOXaOW4tAv6-DfhI6mLKLrZn23vLjM9J_0leZ7xVHVgjgbpl6VcrVuf68SaTMAdyX-ZBD9lUMNZqUKqeJZh0x2eGQBIeH7A3IUCj4hDiJ3oXLJuD1ErHfc616o5lHc9-TAFthNl4szhA