GET http://localhost/api-process/2/start
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjU1MTIwMTIsImV4cCI6MTY2NTU5ODQxMiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZGV2QGRldi5kZXYifQ.2EBwsgkUjTFGKMx8pkw5c9SicwmetMJJLCI3HLNSNxqWLFpCxaDk9OhTzNlAwe2AdMyPBkpePmJhmdmD8wjIatqv4swIJSn49FdV891EigmsMr8NWhVOXVs4X0GUY9faVrkzpoXYr_hg8OKA2eiSKHPhdtTtnRYQ-Mb1dhs_YWT50WmbkycnATwx9s-9YcHPtXMk0jcEecgTNoEffzHDK8cv8Ag-yrBpBS9w1I0do37HjPNserLu4jtbCSVb3vhaVxxYy_sl104KCsr24HVzhi25pLgb8_0qAkyMT7w6mWiN1b7-FIhv6Cd4tNd7qqQvxzRWVWA7gsjJSEP0Hk09Jg

###
GET http://localhost/api-process/2/next
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjU1MTIwMTIsImV4cCI6MTY2NTU5ODQxMiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZGV2QGRldi5kZXYifQ.2EBwsgkUjTFGKMx8pkw5c9SicwmetMJJLCI3HLNSNxqWLFpCxaDk9OhTzNlAwe2AdMyPBkpePmJhmdmD8wjIatqv4swIJSn49FdV891EigmsMr8NWhVOXVs4X0GUY9faVrkzpoXYr_hg8OKA2eiSKHPhdtTtnRYQ-Mb1dhs_YWT50WmbkycnATwx9s-9YcHPtXMk0jcEecgTNoEffzHDK8cv8Ag-yrBpBS9w1I0do37HjPNserLu4jtbCSVb3vhaVxxYy_sl104KCsr24HVzhi25pLgb8_0qAkyMT7w6mWiN1b7-FIhv6Cd4tNd7qqQvxzRWVWA7gsjJSEP0Hk09Jg

###
