GET http://localhost/api/sql-metadata/index
Accept: application/ld+json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODM5ODc1NDksImV4cCI6MTY4NDA3Mzk0OSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9URUFDSEVSIl0sInVzZXJuYW1lIjoiYWlrdXNAeWFuZGV4LnJ1In0.y6I8GZ8aHgmcaYDlpQXslBIs2wc5ZsihHr--K17o3cd-3WO7cizQ6T58gyaBuj4kQrk9RBcj1zsIOrPgV9XiseS_EHNxgo66ccuEMwRLNP54Ji4sXFJJNPe6C92oLfGcOVyt0BVTi1ctYQmu8x-GBr_gQ0fcIT_-pEiQ0obhDPeyaEn68_Z4l-CJd8W0ie5NX7ZMKU7g6_Yjr6hCFCM3zUpYnUSwgva6n2MsOUZZOY5zJfJZmqEZ3Q7LkhQ4LcMP4tOwwF2h1DJQHrOUR3OikM-vtnkAsJ-_f5ryzu_pTtJ27mdNQJpB4d5nEziOA8h0v7ESNKxIAgJsw_tnSEH91g
