app_api_login:
    path: /api/login
    methods: ['POST']

app_logout:
    path: /api/logout
    methods: ['GET']

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_react_my-profile:
    path: react/my-profile
    controller: \App\Controller\ReactDevPageController::index
    methods: [ 'GET' ]

app_react_practice:
    path: react/my-profile/practice
    controller: \App\Controller\ReactDevPageController::index
    methods: [ 'GET' ]